### ISSUE TITLE
HttpException

### ISSUE THREAD

**Issue by kkrishnan90** [CloudRail/cloudrail-si-android-sdk#12]
Hi, 
I am currently able to use your service completely for my Apps Facebook and Google+ login integration. 
But, when I am testing the app, there's been a continuous problem on the cloud rail API throwing Httpexception continuously. 
I have tried all means to fix this in my code (thinking different ways to implement things) but nothing works out. 
Here's my scenario. 
1. User taps on any one of the button in login page (Facebook or Google+).
2. I have two Profiles in my code (one for Facebook and the other for Google+). These two profiles are connected with two distinct Thread. 
3. I start the corresponding thread based on user's input (either tap on Facebook or Google+ button).
4. The profile information is retrieved and the user is taken to the next screen. 
5. Now there's a logout button in this screen. When the user taps on it and gets back to the login screen again, and then again tries to login through either Facebook or Google+ button click, then at this point the Http Exception is thrown by the API. 
Also I would appreciate if there's any sample or demo code released for consuming social profile apis. Any particular date when its gonna be released ?

**Comment by FlorianWendel** [comment]
Hi there, someone else encountered a similar problem yesterday. We just released version 2.1.2 where the bug should be fixed. Please update and tell us if it works now for you as well.
A sample app for the Profile interface is in development and will presumably be released early next week.

**Comment by kkrishnan90** [comment]
Hey hi ! 

Tried with 2.1.2
here's the log ... It was working fine for few iterations. When I signed out from Google and Resigned with Facebook again , here's what I get. But again, now a couple of iterations worked great, this was spotted during the 5th or 6th iterations of continuously logging in and out of different accounts.
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-3471
                                                                              Process: cabdigital.socialloginsample, PID: 20003
                                                                              com.cloudrail.si.exceptions.HttpException
                                                                                  at com.cloudrail.si.services.Facebook.login(Facebook.java:453)
                                                                                  at cabdigital.cabdigital.MainActivity$1$1.run(MainActivity.java:64)

```

**Comment by kkrishnan90** [comment]
Tested again ! The problem still prevails when switching to different accounts / providers randomly.
Kindly check at your end and let me know.

**Comment by FlorianWendel** [comment]
I couldn't reproduce it on my side.

The different instances keep separate state, the only thing they share is the WebView which can only be used by one instance at a time. The interaction with it happens in a synchronized block to avoid overlaps even if there are multiple threads running in parallel. So different services should not be able to interfere with each other.

Could you test if the problem persists if you reinitialize the respective service before using it after every switch? Also, are you using the saveAsString and loadAsString methods?

**Comment by kkrishnan90** [comment]
Hi Florian,
Yes I use saveAsString and loadAsString methods to retrieve the profile of the user every time the user opens the app. 
Also yeah even I am not able to reproduce the issue again. But let check for a few days since I've sent it to my testing team for now. Shall we keep this issue open for a day or two until my testing team reverts with a result ?

**Comment by FlorianWendel** [comment]
Absolutely, looking forward to your feedback.

**Comment by kkrishnan90** [comment]
Thanks Florian ! Appreciate your immediate response !

**Comment by kkrishnan90** [comment]
Hi Florian ! 
Thanks for trusting and keeping this issue open for quite some time! 
I am closing this issue as I feel that everything neatly sorted out in your 2.2.0 version! 
Kudos to the entire team again and to you specially on supporting issues with swift response !
