### ISSUE TITLE
Onedrive upload - Parent path does not exist

### ISSUE THREAD

**Issue by p0087** [CloudRail/cloudrail-si-android-sdk#66]
Potentially the same issue as https://github.com/CloudRail/cloudrail-si-android-sdk/issues/65. Can only replicate it on OneDrive.

```
if (!onedrive.exists("/MW")) {
     onedrive.createFolder("/MW");
 }
if (!onedrive.exists("/MW/Video")) {
     onedrive.createFolder("/MW/Video");
}
```

The second createFolder will cause "com.cloudrail.si.exceptions.NotFoundException: Parent path does not exist"

Edit: I'll further add that logging in via webview with onedrive doesn't exit after 2FA. You just get stuck in a Microsoft Account page

**Comment by PatrickStoklasa** [comment]
Hi there,

We are currently working on a OneDrive fix anyway because they seem to have changed sth in the way they want their url parameters to be encoded. This has happened without any notice from their side so we are adjusting as soon as possible. I will validate that the issues you had do not appear in the new version just to be sure.

**Comment by PatrickStoklasa** [comment]
We have released the fix with version 2.16.4. If you still have trouble let me know.

**Comment by p0087** [comment]
Just gave it a shot. Creating folders seems to be fixed, as is uploading. However the webview still doesn't exist on successful login. Still stuck in MS account page.

**Comment by PatrickStoklasa** [comment]
I tried it again myself but it works fine for me. If it is stuck on MS page then maybe the redirect is not performed by MS for some reason. Could you maybe post a screenshot on where it is stuck? Does it happen with every account?

**Comment by p0087** [comment]
![6](https://cloud.githubusercontent.com/assets/19848943/24654268/188fd350-1978-11e7-9fe5-5ff5c37f98c7.png)
![5](https://cloud.githubusercontent.com/assets/19848943/24654271/18a06152-1978-11e7-979c-f8e8b2de58d6.png)
![4](https://cloud.githubusercontent.com/assets/19848943/24654273/18a404c4-1978-11e7-8f7f-4acebb072abd.png)
![3](https://cloud.githubusercontent.com/assets/19848943/24654272/18a2e06c-1978-11e7-8e67-73a944c0ae77.png)
![2](https://cloud.githubusercontent.com/assets/19848943/24654270/189249e6-1978-11e7-8964-45e15682bcb3.png)
![1](https://cloud.githubusercontent.com/assets/19848943/24654269/1890ea56-1978-11e7-9174-da74f7fdabc4.png)

I'm guessing it's screen for authenticator app that breaks it. However I've selected 'No thanks', and it asks it every time, so there's no way around it.

**Comment by PatrickStoklasa** [comment]
I still couldn't really reproduce the exact screens you get. But it appears that there is some wrong redirecting going on. However, if they do not redirect to our redirect url then there is not much we can do from the SDK side at least. 

Have you tried selecting 'Set it up later'? Or maybe opening a support ticket at Microsoft's support could be an option as well.

**Comment by p0087** [comment]
I can't avoid the screen because on each sign in it considers it new and does everything again. But at this point it's definitely something on MS's end and nothing that I can see you getting around (aside from using OneDrive app to authenticate, but that's a whole other thing)

**Comment by PatrickStoklasa** [comment]
I will stress this point again and see if it fits into our roadmap, but for the time being i will consider this closed. Please feel free to keep me updated if there is any response from MS or if you have any other update on this.

**Comment by p0087** [comment]
@PatrickStoklasa the problem is gone since the latest update. Proper flow is restored. Cheers

**Comment by PatrickStoklasa** [comment]
Thanks for letting me know. I don't think we have done anything about it but as long as it works I won't complain.
